name: "Deploy projeto front-end Escalla imobiliária"
on:
  push:
    branches:
      - staging

jobs:
  build_front_end_escalla_staging:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "82.25.69.129"
          username: "root"
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/projetos/front-end-imobiliaria-escalla"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "82.25.69.129"
          username: "root"
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projetos/front-end-imobiliaria-escalla
            npm install
            npm install next react react-dom
            npx next build
            chown -R www-data:www-data .
            
      - name: "Rodar o servidor Next.js"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "82.25.69.129"
          username: "root"
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projetos/front-end-imobiliaria-escalla
            npm run dev & # Inicia o servidor na porta 3000 em segundo plano
