name: "Configurar e reiniciar Nginx para o projeto front-end Escalla imobiliária"

on:
  push:
    branches:
      - staging

jobs:
  configure_nginx:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Conectar via SSH e atualizar a configuração do Nginx"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "82.25.69.129"
          username: "root"
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Copiar a configuração do Nginx para o local correto
            echo "Atualizando a configuração do Nginx..."
            cp /home/ubuntu/projetos/front-end-imobiliaria-escalla/nginx/escalla-imobiliaria.conf /etc/nginx/sites-available/escalla-imobiliaria.conf
            
            # Criar o link simbólico na pasta sites-enabled
            ln -s /etc/nginx/sites-available/escalla-imobiliaria.conf /etc/nginx/sites-enabled/

            # Testar a configuração do Nginx
            nginx -t

            # Reiniciar o Nginx para aplicar as novas configurações
            systemctl restart nginx

      - name: "Verificar o status do Nginx"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "82.25.69.129"
          username: "root"
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Verificar se o Nginx está funcionando corretamente
            systemctl status nginx
